---
title: "CropQuantitativeDataDigest"
author: "Christina Raw"
date: "7/3/2022"
output: html_document
---


# Coarse data digest: how many observations per magpie class?

```{r}
library(dplyr)

library(here)
d <- read.csv(here("Data/01.Processed_Data/04.Magpie_classes",  "Csv_Magpie_Crops_Quantitative_spreadsheet.csv"), row.names = 1) # Load data

magpie_data <- as.data.frame(table(d$magpie_class))


table(d$magpie_class)

unique(d$magpie_class)

x <- d[c(100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 555),]

```




# Detailed data digest: within each magpie class, how many observations per crop?

crop_data <- as.data.frame(table(d$Crop))

# Add column with magpie classes

colnames(crop_data)[1] <- "Crop"
colnames(crop_data)[2] <- "N"


for (i in (1:31)){
  #browser()
  for (j in (1:31)){
    if (crop_data$Crop[i] == magpie$My_crops[j]){
      crop_data$Magpie_class[i] <- magpie$Magpie_classess[j]
    }}}

crop_data <- relocate(crop_data, Magpie_class, .before = Crop)

# Save data frames

write_xlsx(magpie_data, "Outputs/06.Magpie_classes/DataDigest/Excel_DataDigest_MagpieClasses.xlsx")
write.csv(magpie_data, "Outputs/06.Magpie_classes/DataDigest/CSV_DataDigest_MagpieClasses.csv")

write_xlsx(crop_data, "Outputs/06.Magpie_classes/DataDigest/Excel_DataDigest_CropData.xlsx")
write.csv(crop_data, "Outputs/06.Magpie_classes/DataDigest/CSV_DataDigest_CropData.csv")


# Count number of papers per crop ----

papers <- select(d, Crop, Paper_ID)

data_count_1 <- aggregate(data = papers,                  # Count the number of 
                          Paper_ID ~ Crop,                # per crop
                          function(x) length(unique(x)))

crop_Nstudies_Npapers <- merge(crop_data,data_count_1,by="Crop")  # Make table

write_xlsx(crop_Nstudies_Npapers, "Outputs/06.Magpie_classes/DataDigest/Crops_Nstudies_Npapers.xlsx")





