---
title: "Wheigted means digest"
author: "Christina Raw"
date: "17/3/2022"
output: html_document
---

```{r, include = FALSE}

# Load all packages I will need:

library(here) # To tell RMD where to find and store files
library(knitr) # To make RMD tables
library(tidyr) # To tidy data sets
library(dplyr) # To manipulate the data sets
library(ggplot2) # To plot
library(ggpubr) # To arrange plots
library(kableExtra) # To make cool table

```

# Vivid Economics

## Crops weighted means for Vivid Economics focal crops

```{r, echo = FALSE}

# Load data

percentage_vivid <- read.csv( here("Data/01.Processed_Data/05.Analysis", "08.VividEconomicsMeanEffect.csv"), row.names = 1)

LRR_vivid <- read.csv( here("Data/01.Processed_Data/05.Analysis", "08.LRR_VividEconomicsMeanEffect.csv"), row.names = 1)

# Make tables that allign side by side 

kbl(percentage_vivid, caption = "Biodiveristity % change under different agricultural systems and crops") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "float_left")

kbl(LRR_vivid, caption = "Biodiveristity LRR under different maize agricultural systems") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "right")

```
```{r, message = FALSE, echo = FALSE}

# Plot the data

    # Percentage data

ggplot( percentage_vivid, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 5, ncol = 1, scales = "free_x") + 
  xlab("Wheighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( limits = c(-80, 70), breaks= c(-80,-35, -19, -2, 0, 5, 13, 15, 67)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.spacing.y=unit(1.5, "lines"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
   geom_vline(xintercept = 0) +
  labs(title = "Biodiveristity % change under different agricultural systems and crops")

  # LRR data and back-transformed LRR data

LRR_plot <- ggplot( LRR_vivid, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  xlab("LRR weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
  geom_vline(xintercept = 0) +
  coord_fixed(ratio = 0.025) +
  labs(title = "Biodiveristity LRR under different maize agricultural systems")

perc_plot <- ggplot( LRR_vivid, aes(Percentage, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  xlab("% Change weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) + 
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7),
         plot.title =  element_text(vjust = 10, hjust = 0)) +
  geom_vline(xintercept = 0) +
  coord_fixed(ratio = 3.5) +
  labs(title = "Back transformed biodiversity LRR under different maize agricultural systems")

ggarrange(LRR_plot, NULL, perc_plot, ncol = 1, heights = c(1, 0.01, 1))
```

## Magpie classes weighted means for Vivid Economics focal crops

```{r, echo = FALSE}

# Load data

magpie_percentage_vivid <- read.csv( here("Data/01.Processed_Data/05.Analysis/01.Magpie", "08.VividEconomicsMeanEffect.csv"), row.names = 1)

magpie_LRR_vivid <- read.csv(here("Outputs/07.Analysis/01.Magpie", "08.VividEconomicsMeanCereals.csv"), row.names = 1)

# Make tables with data that align side by side 

kbl(magpie_percentage_vivid, caption = "Biodiveristity % change under different agricultural systems and crops") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "float_left")

kbl(magpie_LRR_vivid, caption = "Biodiveristity LRR under different cereal agricultural systems") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "right")

```
```{r, echo = FALSE, message = FALSE}

# Plot 
  
  # Percentage data

ggplot( magpie_percentage_vivid, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 5, ncol = 1, scales = "free_x") + 
  xlab("Wheighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( limits = c(-80, 70), breaks= c(-80,-35, -19, -2, 0, 5, 13, 15, 67)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.spacing.y=unit(1.5, "lines"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
   geom_vline(xintercept = 0) +
  labs(title = "Biodiveristity % change under different agricultural systems and crops")

  # LRR data and back-transformed LRR data

LRR_plot <- ggplot( magpie_LRR_vivid, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  xlab("LRR weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7),
         plot.title =  element_text(hjust = 0.5)) +
  geom_vline(xintercept = 0) +
  coord_fixed(ratio = 0.025) +
  labs(title = "Biodiveristity LRR under different cereal agricultural systems")

perc_plot <- ggplot( magpie_LRR_vivid, aes(Percentage, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  xlab("% Change weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) + 
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7),
         plot.title =  element_text(vjust = 10, hjust = 0)) +
  geom_vline(xintercept = 0) +
  coord_fixed(ratio = 3.5) +
  labs(title = "Back transformed biodiversity LRR under different maize agricultural systems")

ggarrange(LRR_plot, perc_plot, ncol = 1)
```

# Whole dataset 

## Crops weighted means for the whole dataset

```{r, echo = FALSE}

# Load data

percent <- read.csv( here("Data/01.Processed_Data/05.Analysis", "07.CompleteDataMeanEffect.csv"), row.names = 1)

LRR <-  read.csv(here("Data/01.Processed_Data/05.Analysis", "07.LRR_CompleteDataMeanEffect.csv"), row.names = 1)

# Make tables that align side by side

kbl(percent, caption = "Biodiveristity % change under different agricultural systems and crops") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "float_left")

kbl(LRR, caption = "Biodiveristity LRR under different cereal agricultural systems") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "right")
```
```{r, echo = FALSE, message = FALSE}

# Plot 

  # Percentage data

ggplot( percent, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 7, ncol = 1, scales = "free_x")  +
  xlab("Wheighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( limits = c(-80, 70)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
  geom_vline(xintercept = 0) +
  labs(title = "Biodiveristity % change under different agricultural systems and crops")

  # LRR data and back-transformed LRR data 

LRR_plot <- ggplot( LRR, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 3, ncol = 1) +
  xlab("LRR weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
  geom_vline(xintercept = 0) +
  labs(title = "Biodiveristity LRR under different maize and straw cereals agricultural systems") +
  coord_fixed( ratio = 0.025)

perc_plot <- ggplot( LRR, aes(Percentage, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 3, ncol = 1) +
  xlab("% Change weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
  geom_vline(xintercept = 0) +
  labs(title = "Back transformed biodiversity LRR under different cereal agricultural systems") +
  coord_fixed( ratio = 3.5)

ggarrange(LRR_plot, perc_plot, ncol = 1)

```

## Magpie classes weighted means for teh whole dataset

```{r, echo = FALSE}

magpie_perc <- read.csv( here("Data/01.Processed_Data/05.Analysis/01.Magpie", "07.CompleteDataMeanEffect.csv"), row.names = 1)

magpie_LRR <- read.csv( here("Data/01.Processed_Data/05.Analysis/01.Magpie", "07.LRR_CompleteDataMeanEffect.csv"), row.names = 1)
  
```

```{r, results='asis', echo = FALSE}

kbl(magpie_perc, caption = "Biodiveristity % change under different agricultural systems and commodities") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "float_left")

kbl(magpie_LRR, caption = "Biodiveristity LRR under different cereal agricultural systems") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "right")
```
```{r,echo = FALSE,  message = FALSE}

ggplot( magpie_perc, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 7, ncol = 1, scales = "free_x")  +
  xlab("Wheighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( limits = c(-80, 70)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
  geom_vline(xintercept = 0) +
  labs(title = "Biodiveristity % change under different agricultural systems and crops")

LRR_plot <- ggplot( magpie_LRR, aes(wheighted.mean, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 3, ncol = 1) +
  xlab("LRR weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
  geom_vline(xintercept = 0) +
  labs(title = "Biodiveristity LRR under different cereal agricultural systems") +
  coord_fixed( ratio = 0.025)

perc_plot <- ggplot( magpie_LRR, aes(Percentage, size = 1, fill = agricultural_system)) +
  geom_dotplot(dotsize = 0.5) +
  facet_wrap (~ crop, nrow = 3, ncol = 1) +
  xlab("% Change weighted mean") +
  ylab("") +
  scale_y_discrete(breaks=NULL) +
  scale_x_continuous( breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) +
  theme( panel.background = element_blank(),
         axis.line.x.bottom=element_line(color="black"),
         panel.border = element_rect(colour = "black", fill = NA),
         axis.text.x= element_text(size = 7)) +
  geom_vline(xintercept = 0) +
  labs(title = "Back transformed biodiversity LRR under different maize agricultural systems") +
  coord_fixed( ratio = 3.5)

ggarrange(LRR_plot, perc_plot, ncol = 1)

```